# Generated by Django 4.2.4 on 2023-08-15 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certification_link',
            field=models.URLField(default='www.google.com'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date_completed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
