# Generated by Django 4.2.4 on 2023-08-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='graduation_date',
            new_name='beginYear',
        ),
        migrations.AddField(
            model_name='education',
            name='endYear',
            field=models.CharField(default='2020', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.IntegerField(default=9),
        ),
    ]
