# Generated by Django 4.2.4 on 2023-08-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_graduation_date_education_beginyear_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
